/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module fa(a, b, cin, sum, co);
  input a;
  input b;
  wire c1;
  wire c2;
  input cin;
  output co;
  wire s1;
  output sum;
  ha ins1 (
    .a(a),
    .b(b),
    .co(c1),
    .sum(s1)
  );
  ha ins2 (
    .a(cin),
    .b(s1),
    .co(c2),
    .sum(sum)
  );
  orgate ins3 (
    .a(c1),
    .b(c2),
    .y(co)
  );
endmodule

module ha(a, b, sum, co);
  input a;
  input b;
  output co;
  output sum;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(co)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(sum)
  );
endmodule

module orgate(a, b, y);
  input a;
  input b;
  output y;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(b),
    .SLEEP(a),
    .X(y)
  );
endmodule
