/* Generated by Yosys 0.22+29 (git sha1 fc53a0a5c, clang 14.0.0-1ubuntu1 -fPIC -Os) */

module fa(a, b, cin, sum, co);
  input a;
  wire a;
  input b;
  wire b;
  wire c1;
  wire c2;
  input cin;
  wire cin;
  output co;
  wire co;
  wire s1;
  output sum;
  wire sum;
  ha ins1 (
    .a(a),
    .b(b),
    .co(c1),
    .sum(s1)
  );
  ha ins2 (
    .a(cin),
    .b(s1),
    .co(c2),
    .sum(sum)
  );
  orgate ins3 (
    .a(c1),
    .b(c2),
    .y(co)
  );
endmodule

module ha(a, b, sum, co);
  input a;
  wire a;
  input b;
  wire b;
  output co;
  wire co;
  output sum;
  wire sum;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(b),
    .B(a),
    .X(co)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(b),
    .B(a),
    .X(sum)
  );
endmodule

module orgate(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(b),
    .SLEEP(a),
    .X(y)
  );
endmodule
